### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by IamMusavaRibica** [glubsy/livestream_saver#13]
Hello, when I tried to download a livestream, I got this error:
```
2021-08-10 19:03:01,270 - INFO - livestream_saver.cookies - No cookie path submitted. Using a blank cookie jar.
2021-08-10 19:03:01,462 - INFO - download.PbA78pEwsKw - Will start downloading from segment number 0.
2021-08-10 19:03:01,965 - INFO - download.PbA78pEwsKw - Stream seems to be viewed live. Good.
2021-08-10 19:03:01,965 - INFO - download.PbA78pEwsKw - Stream status Status.OK
2021-08-10 19:03:01,966 - ERROR - livestream_saver - apply_descrambler() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver.py", line 588, in main
    error = args["func"](config, args)
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver.py", line 371, in download_mode
    dl.download(config.getfloat("download", "scan_delay", vars=args))
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver\download.py", line 669, in download
    self.update_download_urls()
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver\download.py", line 606, in update_download_urls
    video_quality, audio_quality = self.get_best_streams(
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver\download.py", line 918, in get_best_streams
    avail_streams = self.streams
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver\download.py", line 284, in streams
    return pytube.StreamQuery(self.fmt_streams)
  File "D:\YoutubeDL\Livestreamsaver\livestream_saver\download.py", line 862, in fmt_streams
    pytube.extract.apply_descrambler(self.player_config_args, fmt)
TypeError: apply_descrambler() takes 1 positional argument but 2 were given
```

**Comment by IamMusavaRibica** [comment]
Command used: `python livestream_saver.py download VIDEO_URL`
Not sure if this is related but uying `py` instead of `python` commands gives this output: `Unable to create process using '/bin/env python3 livestream_saver.py download VIDEO_URL'`

**Comment by glubsy** [comment]
You are most likely using the wrong `pytube` package version. I suspect you have it installed system-wide and are using the latest version, which currently does not work with livestream_saver (I need to work on updating the code to handle newer versions).

You should use a virtual environment to install the specific version required, as written in requirements.txt. See the Readme.md for details:

```
virtualenv -p python3 --system-site-packages venv
source ./venv/bin/activate
pip3 install -r requirements.txt
```

**Comment by glubsy** [comment]
Actually maybe the Readme should not suggest using `--system-site-packages` flag. I'll remove it. 

As for the other issue, I'll remove the shebang which may cause issue in Windows.

**Comment by IamMusavaRibica** [comment]
Hello, yeah I already had pytube installed but I haven't used a venv so
thats why it might have catched the wrong version

uto, 10. kol 2021. 23:01 Fuan ***@***.***> je napisao:
