### ISSUE TITLE
merging error

### ISSUE THREAD

**Issue by gskvhfk** [glubsy/livestream_saver#26]
I have problem in merging please sort out

C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_19gEHNEkakM{19gEHNEkakM}
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 18, in get_metadata_info
    with open(path / "metadata.json", 'r', encoding='utf-8') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Downlo
ads\\livestream_saver-main\\livestream_saver-main\\stream_capture_19gEHNEkakM{19
gEHNEkakM}\\metadata.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 440, in merge_mode
    info = get_metadata_info(data_path)
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 21, in get_metadata_info
    logger.exception(f"Exception while trying to load metadata.json: {e}")
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1469, in excepti
on
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1577, in _log
    self.handle(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1649, in callHan
dlers
    hdlr.handle(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 950, in handle
    self.emit(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1182, in emit
    self.stream = self._open()
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Downlo
ads\\livestream_saver-main\\livestream_saver-main\\stream_capture_19gEHNEkakM{19
gEHNEkakM}\\merge.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "livestream_saver.py", line 683, in <module>
    exit(main())
  File "livestream_saver.py", line 660, in main
    logger.exception(e)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1469, in excepti
on
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1577, in _log
    self.handle(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1649, in callHan
dlers
    hdlr.handle(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 950, in handle
    self.emit(record)
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1182, in emit
    self.stream = self._open()
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Downlo
ads\\livestream_saver-main\\livestream_saver-main\\stream_capture_19gEHNEkakM{19
gEHNEkakM}\\merge.log'

**Comment by glubsy** [comment]
Your target directory should be `stream_capture_19gEHNEkakM` not `stream_capture_19gEHNEkakM{19gEHNEkakM}`.

**Comment by gskvhfk** [comment]
Still i am getting error
C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_19gEHNEkakM
2021-11-11 18:05:32,474 - ERROR - livestream_saver.merge - Exception while tryin
g to load metadata.json: [Errno 2] No such file or directory: 'C:\\Users\\USER\\
Downloads\\livestream_saver-main\\livestream_saver-main\\stream_capture_19gEHNEk
akM\\metadata.json'
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 18, in get_metadata_info
    with open(path / "metadata.json", 'r', encoding='utf-8') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Downlo
ads\\livestream_saver-main\\livestream_saver-main\\stream_capture_19gEHNEkakM\\m
etadata.json'
2021-11-11 18:05:32,490 - ERROR - livestream_saver - 'id'
Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 441, in merge_mode
    written_file = merge(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 207, in merge
    logger = logging.getLogger("download" + "." + info['id'])
KeyError: 'id'

**Comment by glubsy** [comment]
That is normal if you are missing the metadata.json file that should be in the directory. I'll see if I can patch this to allow merging without the metadata file.

**Comment by gskvhfk** [comment]
i tried once gain its shoC:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_PP0S1T1uvWA
2021-11-11 18:25:35,254 - WARNING - download.PP0S1T1uvWA - Number of audio and v
ideo segments do not match.
2021-11-11 18:25:35,271 - ERROR - livestream_saver - [WinError 2] The system can
not find the file specified
Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 441, in merge_mode
    written_file = merge(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 241, in merge
    vid_props = probe(video_files[0])
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 171, in probe
    probeproc = subprocess.run(probecmd, capture_output=True, text=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_chil
d
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_19gEHNEkakM
2021-11-11 18:25:51,208 - ERROR - livestream_saver - [WinError 2] The system can
not find the file specified
Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 441, in merge_mode
    written_file = merge(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 241, in merge
    vid_props = probe(video_files[0])
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 171, in probe
    probeproc = subprocess.run(probecmd, capture_output=True, text=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_chil
d
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specifiedws different error can u please look in

**Comment by gskvhfk** [comment]
I TRIED ANOTHER FILE BUT ITS DIFFERENT ERROR 

C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_PP0S1T1uvWA
2021-11-11 18:25:35,254 - WARNING - download.PP0S1T1uvWA - Number of audio and v
ideo segments do not match.
2021-11-11 18:25:35,271 - ERROR - livestream_saver - [WinError 2] The system can
not find the file specified
Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 441, in merge_mode
    written_file = merge(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 241, in merge
    vid_props = probe(video_files[0])
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 171, in probe
    probeproc = subprocess.run(probecmd, capture_output=True, text=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_chil
d
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_19gEHNEkakM
2021-11-11 18:25:51,208 - ERROR - livestream_saver - [WinError 2] The system can
not find the file specified
Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 441, in merge_mode
    written_file = merge(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 241, in merge
    vid_props = probe(video_files[0])
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 171, in probe
    probeproc = subprocess.run(probecmd, capture_output=True, text=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_chil
d
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by glubsy** [comment]
You need to have ffprobe installed on your system. It should be installed alongside ffmpeg usually. No idea how that works on Windows. You need to make sure ffprobe is in your PATH environment variable.

**Comment by glubsy** [comment]
If for whatever reason you cannot use ffprobe, I just pushed commit https://github.com/glubsy/livestream_saver/commit/122bc5ed4c2deb922efad56f8b3464c0c4246964 which should ignore the error and complete the merge process anyway. Let me know if you get other errors.

**Comment by gskvhfk** [comment]
the video file got merged but audio is not merged it shows error
C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main>python lives
tream_saver.py merge C:\Users\USER\Downloads\livestream_saver-main\livestream_sa
ver-main\stream_capture_19gEHNEkakM
2021-11-11 21:25:49,260 - ERROR - download.19gEHNEkakM - Failed to use ffprobe:
[WinError 2] The system cannot find the file specified.
2021-11-11 21:25:49,284 - ERROR - download.19gEHNEkakM - Failed to use ffprobe:
[WinError 2] The system cannot find the file specified.
2021-11-11 21:25:49,285 - INFO - download.19gEHNEkakM - Trying concatenation met
hod: "concat".
2021-11-11 21:26:04,074 - ERROR - livestream_saver - [WinError 2] The system can
not find the file specified
Traceback (most recent call last):
  File "livestream_saver.py", line 655, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 441, in merge_mode
    written_file = merge(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 260, in merge
    ffmpeg_output_path_video = concat(
  File "C:\Users\USER\Downloads\livestream_saver-main\livestream_saver-main\live
stream_saver\merge.py", line 135, in concat
    cproc = subprocess.run(
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_chil
d
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by glubsy** [comment]
You need to make sure ffmpeg is in installed, and the path to the program is your PATH. 
I'll push a patch to show a more explicit message whenever ffmpeg cannot be found.

**Comment by gskvhfk** [comment]
Thanks i downloaded ffmeg and files got merged
