### ISSUE TITLE
Reports successful download although merging failed

### ISSUE THREAD

**Issue by chbndrhnns** [glubsy/livestream_saver#3]
I downloaded a stream and in the end, I see a success message despite of exceptions. The mp4 file is empty.

```
2021-04-21 21:54:42,556 - INFO - download.bvxA9yzUpSo - Downloading segment 6876...
2021-04-21 21:54:50,007 - ERROR - download.bvxA9yzUpSo - IncompleteRead(14323 bytes read)
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 560, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 527, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 592, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 562, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/homes/jo/tools/livestream_saver/livestream_saver/download.py", line 359, in do_download
    if not self.write_to_file(in_stream, video_segment_filename):
  File "/volume1/homes/jo/tools/livestream_saver/livestream_saver/download.py", line 520, in write_to_file
    buf = fsrc_read(length)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 497, in readinto
    return self._readinto_chunked(b)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/http/client.py", line 608, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(14323 bytes read)
2021-04-21 21:54:50,010 - INFO - download.bvxA9yzUpSo - IncompleteRead(14323 bytes read)
2021-04-21 21:54:50,144 - INFO - livestream_saver.util - GET https://www.youtube.com/watch?v=bvxA9yzUpSo
2021-04-21 21:54:50,356 - WARNING - download.bvxA9yzUpSo - The stream is not live anymore. Done.
2021-04-21 21:54:50,356 - INFO - download.bvxA9yzUpSo - Finished downloading bvxA9yzUpSo.
2021-04-21 21:55:45,666 - INFO - download.bvxA9yzUpSo - Successfully wrote file ".//stream_capture_bvxA9yzUpSo/BVH e.V. [2021-04-21] BVH Börsenführerschein Teil 3 - Futures, Optionen & Zertifikate_[1080]_bvxA9yzUpSo.mp4".

```

**Comment by glubsy** [comment]
These exceptions are normal for the last segment file (6876 in your case), so these should not be a problem.

I'll work on better ffmpeg error handling and log messages.

**Comment by chbndrhnns** [comment]
I am fine with the exception when the stream ended but I found it confusing to see "Successfully wrote file" which was not the case
