### ISSUE TITLE
Downloading fails if the stream quality is higher than 1080p

### ISSUE THREAD

**Issue by IffyWiFi** [glubsy/livestream_saver#33]
I get this error when trying to download livestreams which are at a quality higher than 1080p. Have tried --max-video-quality 1080, but get the same error.

> python livestream_saver.py monitor https://www.youtube.com/c/DrLupo

```
2022-01-07 17:18:25,046 - DEBUG - livestream_saver.request - CookieJar after extract_cookies(): <MozillaCookieJar[<Cookie CONSENT=YES+cb.20210328-17-p0.en+F+581 for .youtube.com/>, <Cookie GPS=1 for .youtube.com/>, <Cookie VISITOR_INFO1_LIVE=I7ayvkFUTlg for .youtube.com/>, <Cookie YSC=aWqWi4EP6lQ for .youtube.com/>]>
2022-01-07 17:18:26,760 - ERROR - livestream_saver - Got error in stream download but continuing...
 'NoneType' object has no attribute 'url'
Traceback (most recent call last):
  File "D:\livestream_saver-main\livestream_saver.py", line 529, in monitor_mode
    livestream.download()
  File "D:\livestream_saver-main\livestream_saver\download.py", line 812, in download
    self.update_download_urls()
  File "D:\livestream_saver-main\livestream_saver\download.py", line 734, in update_download_urls
    self.video_base_url = self.video_itag.url
AttributeError: 'NoneType' object has no attribute 'url'
2022-01-07 17:18:26,761 - INFO - livestream_saver.monitor - Sleeping for 18.47 minutes (1108.35 seconds)...
```

Full log
https://pastebin.com/zY5FnSgL
<br/>

> python livestream_saver.py download https://www.youtube.com/watch?v=eCar7tz_J6I

```
2022-01-07 17:18:49,453 - DEBUG - livestream_saver.request - CookieJar after extract_cookies(): <MozillaCookieJar[<Cookie CONSENT=YES+cb.20210328-17-p0.en+F+809 for .youtube.com/>, <Cookie GPS=1 for .youtube.com/>, <Cookie VISITOR_INFO1_LIVE=QG44tSXh0hY for .youtube.com/>, <Cookie YSC=5gibyeIC6tI for .youtube.com/>]>
2022-01-07 17:18:50,639 - INFO - download.eCar7tz_J6I - Selected video None
2022-01-07 17:18:50,639 - INFO - download.eCar7tz_J6I - selected audio None
2022-01-07 17:18:50,963 - DEBUG - download.eCar7tz_J6I - Selected video itag None / Selected audio itag:None
2022-01-07 17:18:50,963 - ERROR - livestream_saver - 'NoneType' object has no attribute 'url'
Traceback (most recent call last):
  File "D:\livestream_saver-main\livestream_saver.py", line 964, in main
    error = args["func"](config, args)
  File "D:\livestream_saver-main\livestream_saver.py", line 615, in download_mode
    dl.download(config.getfloat("download", "scan_delay", vars=args))
  File "D:\livestream_saver-main\livestream_saver\download.py", line 812, in download
    self.update_download_urls()
  File "D:\livestream_saver-main\livestream_saver\download.py", line 734, in update_download_urls
    self.video_base_url = self.video_itag.url
AttributeError: 'NoneType' object has no attribute 'url'
```
Full log
https://pastebin.com/gTBjGeJz

**Comment by glubsy** [comment]
It does not seem to be related to video quality at all. 
The innertube API did not return any download URL for each stream (itag) for some unknown reason.
A workaround would be to get those download URLs from the MPD. I'll work on that fix.

**Comment by IffyWiFi** [comment]
That's great. Thanks for all your hard work on this brilliant and incredibly useful program!
Strange, I could only produce the bug on 1440p and higher resolution streams, but could easily be mistaken.

**Comment by glubsy** [comment]
> Strange, I could only produce the bug on 1440p and higher resolution streams, but could easily be mistaken.

Interesting. Perhaps the Android client is not supposed to load videos beyond a certain resolution, and that would explain why the innertube API does not return any URL for the android client.
Anyway, I consider this to be a bug in pytube for which I have to write yet another workaround. Will push a patch soon.

**Comment by glubsy** [comment]
I believe this is now fixed.

Feel free to re-open this ticket if you encounter any related issue.

Thanks for reporting!
