### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by Bigpupik9** [glubsy/livestream_saver#36]
python3.8 livestream_saver.py download https://www.youtube.com/watch?v=u3jsBaC029Q
2022-02-28 21:09:52,166 - INFO - livestream_saver.cookies - No cookie path submitted. Using a blank cookie jar.
2022-02-28 21:09:52,956 - WARNING - download.u3jsBaC029Q - An output directory already existed. We assume a failed download attempt. Last segment available was 1.
2022-02-28 21:09:52,957 - INFO - download.u3jsBaC029Q - Will start downloading from segment number 0.
2022-02-28 21:09:53,261 - INFO - download.u3jsBaC029Q - Stream seems to be viewed live. Good.
2022-02-28 21:09:53,262 - INFO - download.u3jsBaC029Q - Stream status Status.OK
2022-02-28 21:09:55,603 - ERROR - livestream_saver - 'NoneType' object has no attribute 'span'
Traceback (most recent call last):
  File "livestream_saver.py", line 963, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 614, in download_mode
    dl.download(config.getfloat("download", "scan_delay", vars=args))
  File "/media/sf_Downloads/livestream_saver-main/livestream_saver/download.py", line 942, in download
    self.update_download_urls()
  File "/media/sf_Downloads/livestream_saver-main/livestream_saver/download.py", line 831, in update_download_urls
    video_quality, audio_quality = self.get_best_streams(
  File "/media/sf_Downloads/livestream_saver-main/livestream_saver/download.py", line 1224, in get_best_streams
    avail_streams = self.streams
  File "/media/sf_Downloads/livestream_saver-main/livestream_saver/download.py", line 480, in streams
    query = pytube.StreamQuery(self.fmt_streams)
  File "/media/sf_Downloads/livestream_saver-main/livestream_saver/download.py", line 1168, in fmt_streams
    pytube.extract.apply_signature(self.player_config_args, fmt, self.js)
  File "/home/bigpupik/.local/lib/python3.8/site-packages/pytube/extract.py", line 442, in apply_signature
    cipher = Cipher(js=js)
  File "/media/sf_Downloads/livestream_saver-main/livestream_saver/download.py", line 121, in patched__init__
    self.throttling_plan = pytube.cipher.get_throttling_plan(js)
  File "/home/bigpupik/.local/lib/python3.8/site-packages/pytube/cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/home/bigpupik/.local/lib/python3.8/site-packages/pytube/cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

**Comment by glubsy** [comment]
This is a bug in pytube. Have you installed the required version in a virtual environment as specified in the Readme.md? 

If you are not using a virtual environment, at least make sure you're using the required pytube version.

**Comment by Bigpupik9** [comment]
It works fine in virtual environment. Thank you for your time.
