### ISSUE TITLE
Raised JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by n-dv** [glubsy/livestream_saver#39]
The issue just started today. I tried multiple channels and confirmed the same issue. Basically JSON decoding is failed. Could someone confirm it?

Using the latest code and it runs on Windows.

```
F:\livestream_saver>python3 livestream_saver.py monitor --delete-source https://www.youtube.com/c/FoxNews
2022-04-25 22:52:33,827 - INFO - livestream_saver.cookies - No cookie path submitted. Using a blank cookie jar.
2022-04-25 22:52:34,014 - INFO - livestream_saver - Monitoring channel: FoxNews
2022-04-25 22:52:34,441 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 234985 (char 234984)
2022-04-25 22:52:34,443 - CRITICAL - livestream_saver.monitor - Got an invalid upcoming JSON: Extra data: line 1 column 234985 (char 234984)
2022-04-25 22:52:34,444 - INFO - livestream_saver.monitor - Currently listed public upcoming videos: 0

2022-04-25 22:52:34,873 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 137908 (char 137907)
2022-04-25 22:52:34,874 - CRITICAL - livestream_saver.monitor - Got an invalid community JSON: Extra data: line 1 column 137908 (char 137907)
2022-04-25 22:52:34,874 - INFO - livestream_saver.monitor - Currently listed community videos: 0

2022-04-25 22:52:35,296 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 234985 (char 234984)
2022-04-25 22:52:35,297 - CRITICAL - livestream_saver.monitor - Got an invalid public JSON: Extra data: line 1 column 234985 (char 234984)
2022-04-25 22:52:35,297 - INFO - livestream_saver.monitor - Currently listed public videos: 0

2022-04-25 22:52:35,301 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 234985 (char 234984)
2022-04-25 22:52:35,302 - ERROR - livestream_saver - Extra data: line 1 column 234985 (char 234984)
Traceback (most recent call last):
  File "livestream_saver.py", line 485, in monitor_mode
    "Live videos found for channel "
  File "F:\livestream_saver\livestream_saver\monitor.py", line 45, in get_channel_name
    _json = self.public_json
  File "F:\livestream_saver\livestream_saver\monitor.py", line 98, in public_json
    self._public_json = extract.str_as_json(
  File "F:\livestream_saver\livestream_saver\extract.py", line 83, in str_as_json
    j = loads(string)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 234985 (char 234984)
2022-04-25 22:52:35,304 - INFO - livestream_saver.monitor - Sleeping for 18.40 minutes (1104.16 seconds)...
Traceback (most recent call last):
  File "livestream_saver.py", line 991, in <module>
    exit(main())
  File "livestream_saver.py", line 963, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 495, in monitor_mode
    wait_block(min_minutes=scan_delay, variance=3.5)
  File "F:\livestream_saver\livestream_saver\monitor.py", line 563, in wait_block
    sleep(wait_time_sec)
KeyboardInterrupt
^C
```

**Comment by jsinghjr2** [comment]
I'm getting the same error on linux debian 11 with python 3.9.2
`2022-04-25 20:38:53,944 - WARNING - livestream_saver.cookies - <Cookie PREF=f6=80&tz=UTC&hl=en for .youtube.com/> is expired (0)! Might want to renew it.
2022-04-25 20:38:53,944 - WARNING - livestream_saver.cookies - <Cookie YSC=NuQ9JEPV2xs for .youtube.com/> is expired (0)! Might want to renew it.
2022-04-25 20:38:55,260 - INFO - livestream_saver - Monitoring channel: CONQUESTCOMICS
2022-04-25 20:38:55,494 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 274087 (char 274086)
2022-04-25 20:38:55,495 - CRITICAL - livestream_saver.monitor - Got an invalid upcoming JSON: Extra data: line 1 column 274087 (char 274086)
2022-04-25 20:38:55,495 - INFO - livestream_saver.monitor - Currently listed public upcoming videos: 0

2022-04-25 20:38:55,614 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 59122 (char 59121)
2022-04-25 20:38:55,614 - CRITICAL - livestream_saver.monitor - Got an invalid community JSON: Extra data: line 1 column 59122 (char 59121)
2022-04-25 20:38:55,615 - INFO - livestream_saver.monitor - Currently listed community videos: 0

2022-04-25 20:38:55,785 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 274087 (char 274086)
2022-04-25 20:38:55,786 - CRITICAL - livestream_saver.monitor - Got an invalid public JSON: Extra data: line 1 column 274087 (char 274086)
2022-04-25 20:38:55,787 - INFO - livestream_saver.monitor - Currently listed public videos: 0

2022-04-25 20:38:55,789 - CRITICAL - livestream_saver.extract - Error loading JSON from string: Extra data: line 1 column 274087 (char 274086)
2022-04-25 20:38:55,790 - ERROR - livestream_saver - Extra data: line 1 column 274087 (char 274086)
Traceback (most recent call last):
  File "/home/abrowncbr/apps/livestream_saver/livestream_saver.py", line 486, in monitor_mode
    f"\"{ch.get_channel_name()}\": "
  File "/home/abrowncbr/apps/livestream_saver/livestream_saver/monitor.py", line 45, in get_channel_name
    _json = self.public_json
  File "/home/abrowncbr/apps/livestream_saver/livestream_saver/monitor.py", line 98, in public_json
    self._public_json = extract.str_as_json(
  File "/home/abrowncbr/apps/livestream_saver/livestream_saver/extract.py", line 83, in str_as_json
    j = loads(string)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 274087 (char 274086)
2022-04-25 20:38:55,824 - INFO - livestream_saver.monitor - Sleeping for 4.13 minutes (247.73 seconds)...

`

**Comment by Benderz** [comment]
same on Windows 11 1903, Python 3.9.12

**Comment by glubsy** [comment]
Thanks for reporting. This should be fixed by ee2a9fe3934d716c47a2723902a56084d4583422.

**Comment by ntomita** [comment]
@glubsy It's fixed! Thank you!

**Comment by n-dv** [comment]
Perfect, I confirmed the commit fixed it. I'm closing the issue.
