### ISSUE TITLE
ERROR - livestream_saver - apply_descrambler() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by axcore** [glubsy/livestream_saver#41]
Linux Mint 20.3, livestream_saver.py commit https://github.com/glubsy/livestream_saver/commit/ee2a9fe3934d716c47a2723902a56084d4583422

`python3 livestream_saver.py download https://www.youtube.com/watch?v=QtBWg6j8yzs
2022-05-05 12:05:29,838 - INFO - livestream_saver.cookies - No cookie path submitted. Using a blank cookie jar.
2022-05-05 12:05:30,079 - WARNING - download.QtBWg6j8yzs - An output directory already existed. We assume a failed download attempt. Last segment available was 1.
2022-05-05 12:05:30,079 - INFO - download.QtBWg6j8yzs - Will start downloading from segment number 0.
2022-05-05 12:05:30,315 - INFO - download.QtBWg6j8yzs - Stream seems to be viewed live. Good.
2022-05-05 12:05:30,316 - INFO - download.QtBWg6j8yzs - Stream status Status.OK
2022-05-05 12:05:30,316 - ERROR - livestream_saver - apply_descrambler() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "livestream_saver.py", line 963, in main
    error = args["func"](config, args)
  File "livestream_saver.py", line 614, in download_mode
    dl.download(config.getfloat("download", "scan_delay", vars=args))
  File "/home/ra/Local/Downloads/Direct/livestream_saver-main/livestream_saver/download.py", line 964, in download
    self.update_download_urls()
  File "/home/ra/Local/Downloads/Direct/livestream_saver-main/livestream_saver/download.py", line 853, in update_download_urls
    video_quality, audio_quality = self.get_best_streams(
  File "/home/ra/Local/Downloads/Direct/livestream_saver-main/livestream_saver/download.py", line 1246, in get_best_streams
    avail_streams = self.streams
  File "/home/ra/Local/Downloads/Direct/livestream_saver-main/livestream_saver/download.py", line 498, in streams
    query = pytube.StreamQuery(self.fmt_streams)
  File "/home/ra/Local/Downloads/Direct/livestream_saver-main/livestream_saver/download.py", line 1188, in fmt_streams
    pytube.extract.apply_descrambler(self.player_config_args, fmt)
TypeError: apply_descrambler() takes 1 positional argument but 2 were given
`

I tried half a dozen livestreams that are currently broadcasting, with the same result.

**Comment by axcore** [comment]
Closing as duplicate for https://github.com/glubsy/livestream_saver/issues/27.
