### ISSUE TITLE
Merge not working

### ISSUE THREAD

**Issue by Artrix** [glubsy/livestream_saver#42]
I get this error on Python 3.9:

```2022-05-24 20:10:28,887 - INFO - download.spO_hiEoeAM - No missing segment detected. All good.
2022-05-24 20:10:28,887 - INFO - download.spO_hiEoeAM - No missing segment detected. All good.
2022-05-24 20:10:29,067 - DEBUG - download.spO_hiEoeAM - Probed "0000000000_video.ts". codec_name: h264, duration: 0.567, start_time: 0.0.
2022-05-24 20:10:29,185 - DEBUG - download.spO_hiEoeAM - Probed "0000000000_audio.ts". codec_name: aac, duration: 0.580499, start_time: 0.0.
2022-05-24 20:10:29,186 - INFO - download.spO_hiEoeAM - Performing concat method NativeConcatFile
2022-05-24 20:10:29,186 - ERROR - download.spO_hiEoeAM - unsupported operand type(s) for /: 'str' and 'str'
Traceback (most recent call last):
  File "/home/artrix/livestream_saver/livestream_saver/merge.py", line 553, in merge
    concat_video_file = methods[attempt](
  File "/home/artrix/livestream_saver/livestream_saver/merge.py", line 296, in __init__
    super().__init__(*args, **kwargs)
  File "/home/artrix/livestream_saver/livestream_saver/merge.py", line 73, in __init__
    self._final_file: Path = output_dir / \
TypeError: unsupported operand type(s) for /: 'str' and 'str'
2022-05-24 20:10:29,186 - ERROR - livestream_saver - Missing concat video file: None
Traceback (most recent call last):
  File "/home/artrix/livestream_saver/livestream_saver.py", line 963, in main
    error = args["func"](config, args)
  File "/home/artrix/livestream_saver/livestream_saver.py", line 636, in merge_mode
    written_file = merge(
  File "/home/artrix/livestream_saver/livestream_saver/merge.py", line 611, in merge
    raise Exception(f"Missing concat video file: {concat_video_file}")
Exception: Missing concat video file: None```

**Comment by glubsy** [comment]
Thanks for reporting. Looks like an issue in either your config file or a CLI argument. 

I suspect you might have specified "output_dir" somewhere to some blank value? I can only speculate, but if you share your config file and arguments you used, I could better point out what caused the issue.

For now I have added a workaround in c543a5a191fbf0c641451295a9a624439b66c68d which falls back to storing the concat file in the current working directory.
