### ISSUE TITLE
Merge fails (outputs an mp4 without audio)

### ISSUE THREAD

**Issue by dnjulek** [glubsy/livestream_saver#7]
Both, automatic and manual merge produce an mp4 without audio

```
D:\livestream_saver>python merge.py stream_capture_R-wCsDY2jTA
2021-05-24 21:08:01,518 - DEBUG - download.R-wCsDY2jTA - Calling subprocess: ['ffmpeg', '-hide_banner', '-loglevel', 'panic', '-y', '-i', 'D:\\livestream_saver\\stream_capture_R-wCsDY2jTA\\concat_R-wCsDY2jTA_video.ts', '-c', 'copy', 'D:\\livestream_saver\\stream_capture_lIIl4H_k0KY\\R-wCsDY2jTA_video_v2_ffmpeg.mp4']
Traceback (most recent call last):
  File "D:\livestream_saver\merge.py", line 55, in <module>
    written_file = merge.merge(\
  File "D:\livestream_saver\livestream_saver\merge.py", line 118, in merge
    ffmpeg_output_path_video = concat("video", info.get('id'), video_files, data_dir)
  File "D:\livestream_saver\livestream_saver\merge.py", line 64, in concat
    logger.debug("FFmpeg STDERR:\n" + ffmpeg_stderr)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by glubsy** [comment]
Thanks for the report. 

I find it strange that these are different paths while they should be the same directory at least:
```
D:\\livestream_saver\\stream_capture_R-wCsDY2jTA\\concat_R-wCsDY2jTA_video.ts
D:\\livestream_saver\\stream_capture_lIIl4H_k0KY\\R-wCsDY2jTA_video_v2_ffmpeg.mp4
```

I have pushed a fix which should fix the error as well as log ffmpeg's output better. 
You should run the script manually again with `--log DEBUG`. Please let me know if there is any other error.

**Comment by dnjulek** [comment]
Thanks, now it worked without errors.
(The two different paths was my copy and paste mistake)

**Comment by glubsy** [comment]
I see, no worries. Thanks for reporting.
