### ISSUE TITLE
Get error when trying to download: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by hcavanaugh** [glubsy/livestream_saver#82]
When I run the python script to download, or when the download script activates during monitor, I get this error. I have the cookies file directory set up in the config, (config is set in C:\Users\....\.config\livestream_saver\livestream_saver.cfg) I used [this](https://github.com/dandv/convert-chrome-cookies-to-netscape-format) to convert the cookies to a netscape cookies file.

Here is the log:

C:\Users\....\ytdlp_config.json not found. Falling back to using template.
2024-04-17 19:16:49,171 - ERROR - livestream_saver - 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "C:\...\livestream_saver\livestream_saver\download.py", line 1116, in download
    error_code = ydl.download(self.url)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 3572, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 3547, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 1595, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 731, in extract
    self.initialize()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 640, in initialize
    self._real_initialize()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\youtube.py", line 520, in _real_initialize
    self._initialize_pref()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\youtube.py", line 508, in _initialize_pref
    cookies = self._get_cookies('https://www.youtube.com/')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 3571, in _get_cookies
    return LenientSimpleCookie(self._downloader.cookiejar.get_cookie_header(url))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 4082, in cookiejar
    return load_cookies(
           ^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\cookies.py", line 103, in load_cookies
    jar.load()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\cookies.py", line 1308, in load
    for line in f:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\....\Documents\Development\livestream_saver\livestream_saver\livestream_saver.py", line 1054, in main
    error = args["func"](config, args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\....\Documents\Development\livestream_saver\livestream_saver\livestream_saver.py", line 667, in download_mode
    ls.download(config.getfloat("download", "scan_delay", vars=args))
  File "C:\Users\...\Documents\Development\livestream_saver\livestream_saver\download.py", line 1115, in download
    with yt_dlp.YoutubeDL(self.ytdl_opts) as ydl:
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 973, in __exit__
    self.close()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 976, in close
    self.save_cookies()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 969, in save_cookies
    self.cookiejar.save()
    ^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\YoutubeDL.py", line 4082, in cookiejar
    return load_cookies(
           ^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\cookies.py", line 103, in load_cookies
    jar.load()
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\yt_dlp\cookies.py", line 1308, in load
    for line in f:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by glubsy** [comment]
Thanks for reporting the issue and its solution!
